#!/system/bin/sh

if [ ! -f "/data/vendor/wifi/hostapd/hostapd.accept" ]
then
    touch /data/vendor/wifi/hostapd/hostapd.accept
fi
if [ ! -f "/data/vendor/wifi/hostapd/hostapd.conf" ]
then
    touch /data/vendor/wifi/hostapd/hostapd.conf
fi
if [ ! -f "/data/vendor/wifi/hostapd/hostapd.deny" ]
then
    touch /data/vendor/wifi/hostapd/hostapd.deny
fi
chown -R wifi:wifi /data/vendor/wifi/hostapd
chmod 0660 /data/vendor/wifi/hostapd/hostapd.accept
chmod 0660 /data/vendor/wifi/hostapd/hostapd.conf
chmod 0660 /data/vendor/wifi/hostapd/hostapd.deny
sleep 30s
chown -R wifi:wifi /data/vendor/wifi/hostapd
chmod 0660 /data/vendor/wifi/hostapd/hostapd.accept
chmod 0660 /data/vendor/wifi/hostapd/hostapd.conf
chmod 0660 /data/vendor/wifi/hostapd/hostapd.deny
